feednoticias/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    Artisan::call('import:rss');
    return view('index');
});
//Añadimos la ruta del modelo con el controlador
Route::resource('feed', 'feedController');

Route::get('rss', function () {
    Artisan::call('import:rss');
});
//Route::get('/showlist', function () {
//    return view('showlist');
//});
//Route::get('/insert', function () {
//    return view('insert');
//});
//Route::
Route::get('store', 'feedController@store');
//Route::resource('showlist', 'feedController');

feednoticias/app/Feed.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Feed extends Model
{
  //Añadimos los atributos que va a contener nuestro modelo
    protected $fillable = ['title', 'body', 'image', 'source', 'publisher', 'created_at', 'updated_at'];
}

feednoticias/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

feednoticias/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

feednoticias/app/Http/Controllers/FeedController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Feed;
use Illuminate\Database\Query\Builder;
//Se añaden todos los controladores editar, eliminar, insertar... para las noticias
class FeedController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $feeds=Feed::all();
      //dd($feeds);
      return view('showlist',['feeds' => $feeds]);
      //array(‘feed’ => $feeds)
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('insert');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request,[ 'title'=>'required', 'body'=>'required', 'image'=>'required', 'source'=>'required', 'publisher'=>'required']);
      Feed::create($request->all());
      return redirect()->route('index')->with('success','Registro creado satisfactoriamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $feed=Feed::find($id);
      return  view('show',compact('feed'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $feed=Feed::find($id);
      return view('edit',compact('feed'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request,[ 'title'=>'required', 'body'=>'required', 'image'=>'required', 'source'=>'required', 'publisher'=>'required']);

      Feed::find($id)->update($request->all());
      return redirect()->route('index')->with('success','Registro actualizado satisfactoriamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      Feed::find($id)->delete();
      return redirect()->route('index')->with('success','Registro eliminado satisfactoriamente');
    }
}

feednoticias/resources/views/edit.blade.php
@extends('layout.app')
@section('feednoticias', 'Edit')

@section('sidebar')
    @parent

@endsection

@section('content')
    <h2>Editar noticia</h2>
    <div>
      <form action="{{ route('feed.update', $feed->id)}}" method="post" class="col-lg-12">
        {{ csrf_field() }}
        <label class="col-lg-12 col-md-12"> Introduzca el titulo:
          <input class="col-lg-12" name="title" required="true" value="{{ $feed['title'] }}">
        </label>
        <label class="col-lg-12 col-md-12"> Introduzca el cuerpo de la noticia:
          <textarea class="col-lg-12" name="body" rows="8" cols="80" value="{{ $feed['description'] }}" required="true"></textarea>
        </label>
        <label class="col-lg-5 col-md-5"> Introduzca la url de la imagen:
          <input name="image" required="true" value="{{ $feed['image'] }}">
        </label>
        <label class="col-lg-6 col-md-6"> Introduzca el link de la noticia:
          <input name="source" required="true" value="{{ $feed['link'] }}">
        </label>
        <label> Introduzca la url del periodico:
          <input name="publisher" required="true" value="{{ $feed['publisher'] }}">
        </label>
        <input class="col-lg-12 button" type="submit" name="submit" value="Añadir">
      </form>
    </div>
    <div>
      <a href="{{ route('feed.index')}}"
        <button type="button" name="button">Volver</button>
      </a>
    </div>
@endsection

feednoticias/resources/views/index.blade.php
@extends('layout.app')
@yield('index')
@section('feednoticias', 'Index')

@section('sidebar')
    @parent

@endsection

@section('content')
        <a href="{{ route('feed.index')}}"><button>Ver lista</button></a>
        <a href="{{ route('feed.create')}}"><button>Insertar noticia</button></a>
@endsection

feednoticias/resources/views/insert.blade.php
@extends('layout.app')
@section('feednoticias', 'Insert')
@section('sidebar')
    @parent

@endsection

@section('content')
    <h2>Insertar noticia</h2>
    <div>
      <form action="{{ route('feed.store')}}" method="post" class="col-lg-12">
        {{ csrf_field() }}
        <label class="col-lg-12 col-md-12"> Introduzca el titulo:
          <input name="title" required="true" class="col-lg-12 col-md-12">
        </label>
        <label class="col-lg-12 col-md-12"> Introduzca el cuerpo de la noticia:
          <textarea name="body" rows="8" cols="80" placeholder="Escriba la noticia" required="true" class="col-lg-12 col-md-12"></textarea>
        </label>

        <label class="col-lg-5 col-md-5"> Introduzca la url de la imagen:
          <input name="image" required="true">
        </label>
        <label class="col-lg-6 col-md-6"> Introduzca el link de la noticia:
          <input name="source" required="true">
        </label>
        <label> Introduzca la url del periodico:
          <input name="publisher" required="true">
        </label>
        <input class="col-lg-12" type="submit" name="submit" value="Añadir">
      </form>
    </div>
    <div>
      <a href="{{ route('feed.index')}}"
        <button type="button" name="button">Volver</button>
      </a>
    </div>

@endsection

feednoticias/resources/views/layout/app.blade.php
<html>
    <head>
        <title> Feednoticias- @yield('title')</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
    </head>
    <body>
        @section('sidebar')
            <h1 style="text-align:center">Feed noticias</h1>
        @show

        <div class="container">
            @yield('content')
        </div>
    </body>
</html>

feednoticias/resources/views/show.blade.php
@extends('layout.app')
@section('feednoticias', 'Show')
@section('sidebar')
    @parent

@endsection
<style media="screen">
  a{
    text-decoration: none;
  }
</style>
@section('content')
    <h1>Ver noticia</h1>
    <div class="show_new_view">
      <h2>
         {{ $feed['title'] }}
      </h2>
      <p>{{ $feed['description'] }}</p>
      <p>{{ $feed['image'] }}</p>
      <a href="{{ $feed['link'] }}">{{ $feed['link'] }}</a>
      <a href="{{ $feed['publisher'] }}">{{ $feed['publisher'] }}</a>
    </div>
      <div class="show_new_button">
        <a href="{{ route('feed.index')}}"
          <button type="button" name="button">Volver</button>
        </a>
        <a href="{{ Route('feed.edit', $feed->id) }}"
          <button type="button" name="button">Editar</button>
        </a>
        <a href="{{ Route('feed.destroy', $feed->id) }}"
          <button type="button" name="button">Eliminar</button>
        </a>
      </div>
@endsection

feednoticias/resources/views/showlist.blade.php
@extends('layout.app')
@yield('showlist')
@section('feednoticias', 'Showlist')

@section('sidebar')
    @parent
<style media="screen">
  table tr{
    border:1px solid black;
  }
  button{
    width: 100px;
    height: 30px;
  }
  .button_insert{
    margin-left: 75%;
  }
  table{
    margin-top: 1%;
  }
</style>
@endsection

@section('content')
      <h2 class="news">Noticias</h2>
      <a href="{{ Route('feed.create') }}">
        <button type="button" name="button" class="button_insert col-lg-3" >Insertar</button>
      </a>
      <table>
        @foreach ($feeds as $feed)
              <tr>
                <td>
                  {{ $feed['title'] }}
                </td>
                <td>
                  <a href="{{ Route('feed.show', $feed->id) }}">
                    <button type="button" name="button">Leer</button>
                  </a>
                </td>
                <td>
                  <a href="{{ Route('feed.edit', $feed->id) }}">
                    <button type="button" name="button">Editar</button>
                  </a>
                </td>
                <td>
                  <a href="{{ Route('feed.destroy', $feed->id) }}">
                    <button type="button" name="button">Eliminar</button>
                  </a>
                </td>
              </tr>
        @endforeach
      </table>

@endsection